name: vigishield_mobile_app
description: "VigiShield — Sistema Inteligente de Seguridad Doméstica"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # HTTP client
  dio: ^5.7.0

  # Secure token storage
  flutter_secure_storage: ^9.2.2

  # State management
  provider: ^6.1.2

  # Navigation
  go_router: ^14.8.1

  # Camera access
  camera: ^0.11.1

  # Date & number formatting
  intl: ^0.20.2

  # Fonts
  google_fonts: ^6.2.1

  # Shimmer loading effects
  shimmer: ^3.0.0

  # Video player (HLS stream from MediaMTX)
  video_player: ^2.9.2

  # Keep screen on while watching the live stream
  wakelock_plus: ^1.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
